:doctype: book
:nofooter:

= Eugene Malyavko

==== AI Engineer
Location | Minsk, Belarus +
Phone Number | +375(33)3333789 +
Gmail | mailto:boom19507@gmail.com[boom19507@gmail.com] +
Mail | mailto:malyavko14@bk.ru[malyavko14@bk.ru] +
Github | https://github.com/malyavko14[malyavko14] 

[#it-skills]
=== IT Skills
'''
==== Software Development:
*Programming languages:* Python, C++, SQL; +
*Frameworks:* numpy, pandas, matplotlib, OpenCV, Keras; +
*Tools:* Docker, Docker Compose, Git, Gradle, MySQL, PostrageSQL.

==== Operating Systems:
*Linux:* Ubuntu, Mint; +
*Other:* Windows WSL.

[#language-skills]
=== Language Skills
'''
*English:* B1; +
*Ukrainian:* Native; +
*Belarusian:* Native; +
*Russian:* Native.

[#work-experience]
=== Education
'''
2022  ~June~:::  
*Belarusian State University of Informatics and Radioelectronics;* +
Faculty: Faculty of Information Technologies and Control; +
Degree:  Artificial Intelligence. +


[#interests]
=== Personal Interests
'''
*Hobbies:* +
traveling, driving, , self-education, walking, communication, electronics, music, basketball, volleyball.

[#prospects]
=== Prospects
'''
Grow and develop soft and hard skills to correspond to surrounding requirements; +
Take an advantage of doing hard tasks to get higher on the proficiency scale; +
Passion to work with high-loaded, scalable, distributed, real-time information processing systems; +
Desire to improve in the scientific field.
